#!/usr/bin/env bash
set -e

### ===============================
### System Update & Base Utilities
### ===============================
sudo xbps-install -Syu xbps
sudo xbps-install -Sy fastfetch mesa-dri mesa-vulkan-radeon xf86-video-amdgpu wget curl xz p7zip

mkdir -p ~/.local/bin
### ===============================
### Networking (Laptop Friendly)
### ===============================
sudo xbps-install -Sy NetworkManager network-manager-applet

# Disable legacy network services
sudo rm -f /var/service/{dhcpcd,wpa_supplicant}

# Enable NetworkManager
sudo ln -sf /etc/sv/NetworkManager /var/service

### ===============================
### Xorg + XFCE Desktop
### ===============================
sudo xbps-install -Sy \
  xorg \
  xfce4 \
  rofi \
  flameshot \
  gvfs

### ===============================
### Fonts
### ===============================
sudo xbps-install -Sy \
  noto-fonts-ttf \
  noto-fonts-cjk \
  noto-fonts-emoji

### ===============================
### Audio (PipeWire)
### ===============================
sudo xbps-install -Sy \
  pipewire \
  alsa-pipewire \
  wireplumber \
  pavucontrol

# ---- Setup xinitrc ----
sudo ln -sf /etc/sv/dbus /var/service
sudo tee /etc/X11/xinit/xinitrc > /dev/null <<'EOF'
#!/bin/sh
set -e

pipewire &
PIPEWIRE_PID=$!

pipewire-pulse &
PULSE_PID=$!

wireplumber &
WIREPLUMBER_PID=$!

nm-applet &

exec startlxqt
EOF

tee ~/.local/bin/sysinfo > /dev/null <<'EOF'
#!/usr/bin/sh

mb_gb() {
    local a=$1
    if [ $(($a / 1024 / 1024)) -gt 0 ]; then
        echo "$(($a / 1024 / 1024))GiB"
    else
        echo "$(($a / 1024))MiB"
    fi
}

cpu_load() {
    echo $(grep -o "^[^ ]*" /proc/loadavg)
}

cpu_temp() {
    echo $(($(cat /sys/class/thermal/thermal_zone0/temp)/1000))
}

ram_stat() {
    local total=$(awk '/^MemTotal/ {print $2}' /proc/meminfo)
    local avail=$(awk '/^MemAvailable/ {print $2}' /proc/meminfo)
    local free=$(awk '/^MemFree/ {print $2}' /proc/meminfo)
    local buffers=$(awk '/^Buffers/ {print $2}' /proc/meminfo)
    local cached=$(awk '/^Cached/ {print $2}' /proc/meminfo)
    local used=$(($total - $free - $buffers - $cached))

    local total_mbgb=$(mb_gb $total)
    local used_mbgb=$(mb_gb $used)

    echo "$used_mbgb/$total_mbgb"
}

net_stat_file() {
    local file="$(cat /proc/net/dev)"
    local d=$(echo "$file" | awk '$1 ~ /:$/ && $1 != "lo:" {sum += $2} END {print sum}')
    local u=$(echo "$file" | awk '$1 ~ /:$/ && $1 != "lo:" {sum += $10} END {print sum}')
    echo "$d $u"
}

net_stat() {
    local ns1="$(net_stat_file)"
    sleep 1
    local ns2="$(net_stat_file)"
    local d1=$(echo "$ns1" | awk '{print $1}')
    local u1=$(echo "$ns1" | awk '{print $2}')
    local d2=$(echo "$ns2" | awk '{print $1}')
    local u2=$(echo "$ns2" | awk '{print $2}')
    echo "$(($d2-d1)) $(($u2-u1))"
}

sysinfo() {
    local net=$(net_stat)
    local download=$(echo $net | awk '{print $1}')
    local upload=$(echo $net | awk '{print $2}')
    echo "CPU: $(cpu_load)% | Temp: $(cpu_temp)℃ | RAM: $(ram_stat) | Download: $(($download/1000))Kbps | Upload: $(($upload/1000))Kbps"
}

sysinfo
EOF
chmod +x ~/.local/bin/sysinfo # untuk ditampilkan sebagai widget

### ===============================
### Browser (Firefox)
### ===============================
sudo xbps-install -Sy firefox

### ===============================
### Editor (Zed)
### ===============================
curl -f https://zed.dev/install.sh | sh

### ===============================
### Rootless containerization
### ===============================
git clone https://github.com/navetacandra/pocker.git ~/.local/share/pocker
ln -s ~/.local/share/pocker/pocker ~/.local/bin/pocker

### ===============================
### Shell Environment
### ===============================
if ! grep -q '.local/bin' ~/.bashrc 2>/dev/null; then
  echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
fi

### ===============================
### Done
### ===============================
echo "DONE."
