#!/usr/bin/env bash
set -e

### ===============================
### System Update & Base Utilities
### ===============================
sudo xbps-install -Sy xbps
sudo xbps-install -Syu
sudo xbps-install -Sy fastfetch mesa-dri mesa-vaapi mesa-vulkan-radeon xf86-video-amdgpu polkit xdg-desktop-portal xdg-desktop-portal-wlr curl xz p7zip git

mkdir -p ~/.local/bin
### ===============================
### Networking (Laptop Friendly)
### ===============================
sudo xbps-install -Sy NetworkManager network-manager-applet iwd

# Disable legacy network services
sudo rm -f /var/service/{dhcpcd,wpa_supplicant}

# Enable NetworkManager
echo -e "\n[device]\nwifi.backend=iwd" >> /etc/NetworkManager/NetworkManager.conf
sudo ln -sf /etc/sv/NetworkManager /var/service
cat << EOF | sudo tee /etc/resolv.conf > /dev/null
nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 9.9.9.9
EOF

### ===============================
### Xorg + XFCE Desktop
### ===============================
sudo xbps-install -Sy \
  xorg \
  wlr-randr \
  wlrctl \
  wl-clipboard \
  labwc \
  lxqt \
  lxqt-wayland-session \
  lxqt-policykit \
  lxqt-notificationd \
  emptty \
  pcmanfm-qt \
  qterminal \
  grim \
  flameshot \
  gvfs

### ===============================
### Fonts
### ===============================
sudo xbps-install -Sy \
  noto-fonts-ttf \
  noto-fonts-cjk \
  noto-fonts-emoji \
  dejavu-fonts-ttf \
  fontconfig

### ===============================
### Audio (PipeWire)
### ===============================
sudo xbps-install -Sy \
  pipewire \
  alsa-pipewire \
  wireplumber \
  pavucontrol \
  pavucontrol-qt

# ---- Setup Display Manager ----
sudo ln -sf /etc/sv/{dbus,emptty} /var/service

### ===============================
### Browser (Helium)
### ===============================
helium_url=$(curl -s https://api.github.com/repos/imputnet/helium-linux/releases/latest | grep 'x86_64_linux.tar.xz"' | cut -d : -f 2,3 | tr -d \")
helium_file=$(basename $helium_url)
curl -LO $helium_url
tar xfv $helium_file
sudo mv $helium_file /opt/helium
cat << EOF | sudo tee /usr/share/applications/helium.desktop > /dev/null
[Desktop Entry]
Name=Helium
GenericName=Helium Browser
Comment=
Exec=/opt/helium/helium
Type=Application
Categories=Internet;
Icon=application-x-desktop
Terminal=false
EOF

### ===============================
### Editor (Zed)
### ===============================
curl -f https://zed.dev/install.sh | sh

### ===============================
### Shell Environment
### ===============================
if ! grep -q '.local/bin' ~/.bashrc 2>/dev/null; then
  echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
  echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bashrc
fi

### ===============================
### Autostart
### ===============================
mkdir -p ~/.config/autostart
cat << EOF | sudo tee ~/.config/autostart/network.desktop > /dev/null
[Desktop Entry]
Name=Network Manager
GenericName=Network Manager Applet Launcher
Comment=Network Manager Applet Launcher
Exec=nm-applet
Type=Application
Categories=Sound & Video;
Icon=application-x-desktop
Terminal=false
EOF

cat << EOF | sudo tee /usr/local/bin/pipewire-autostart > /dev/null
#!/usr/bin/bash
pipewire &
pipewire-pulse &
wireplumber &
EOF

cat << EOF | sudo tee ~/.config/autostart/pipewire.desktop > /dev/null
[Desktop Entry]
Name=Pipewire
GenericName=Pipewire Launcher
Comment=Pipewire Launcher
Exec=/usr/local/bin/pipewire-autostart
Type=Application
Categories=Sound & Video;
Icon=application-x-desktop
Terminal=false
EOF

### ===============================
### Container
### ===============================
sudo xbps-install -Sy podman podman-compose crun
mkdir -p ~/.config/containers
cat << EOF | sudo tee ~/.config/containers/containers.conf > /dev/null
[engine]
runtime = "crun"
EOF

mkdir -p ~/.distrobox/{fedora,ubuntu,alpine}
cat << EOF | sudo tee ~/.distrobox/distrobox.ini > /dev/null
[fedora]
hostname=fedora
image=docker.io/library/fedora:44
pull=true
nvidia=false
root=false
replace=true
home="/home/naveta/.distrobox/fedora"

[ubuntu]
hostname=ubuntu
image=docker.io/library/ubuntu:26.04
pull=true
nvidia=false
root=false
replace=true
home="/home/naveta/.distrobox/ubuntu"

[alpine]
hostname=alpine
image=docker.io/library/alpine:3
pull=true
nvidia=false
root=false
replace=true
home="/home/naveta/.distrobox/alpine"
EOF

distrobox assemble create --file ~/.distrobox/distrobox.ini

### ===============================
### Done
### ===============================
echo "DONE."
